{% set name = "raven-hydro" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test.pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 498dd7d0193fd9659678919e731b96d69f14479b74b31ec954c05861ebe7d853
#  url: http://raven.uwaterloo.ca/files/v{{ version }}/RavenSource_v{{ version }}.zip
#  sha256: a962f3377425868d9cc535b6858e0457f5307636f99466ee37ab66ecfbcaf35c


build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
#  script:
#    - make  # [not win]
#    - cp ./raven $PREFIX/bin/raven  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python >=3.8
    - hatch-fancy-pypi-readme
    - hatchling
    - libnetcdf
    - pip
    - pybind11
    - python >=3.8
    - scikit-build-core
  run:
    - python >=3.8
    - libnetcdf

test:
  imports:
    - raven_hydro
  commands:
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: http://raven.uwaterloo.ca/
  dev_url: https://chyms.nrc.gc.ca/
  doc_url: http://raven.uwaterloo.ca/files/v{{ version }}/RavenManual_v{{ version }}.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Artistic-2.0
  license_file: LICENSE
  summary: The conda-forge binary for the Raven hydrological model developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
