{% set name = "raven-hydro" %}
{% set version = "0.2.1" %}
{% set sha256 = "e57e2b15f05a807fbffbbc34958b47ad27c8650930d4a438efc67c412d473241" %}
{% set raven_version = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - python
    - hatch-fancy-pypi-readme
    - hatchling
    - libnetcdf
    - pip
    - pybind11
    - python
    - scikit-build-core
    - zlib
  run:
    - python
    - libnetcdf
    - zlib

test:
  imports:
    - raven_hydro
  requires:
    - pip
  commands:
    - pip check
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: http://raven.uwaterloo.ca
  dev_url: https://github.com/Ouranosinc/raven-hydro
  doc_url: http://raven.uwaterloo.ca/files/v{{ raven_version }}/RavenManual_v{{ raven_version }}.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Apache-2.0 and Artistic-2.0
  license_file:
    - LICENSE
    - build/_deps/raven-src/LICENSE
  summary: |
    The Python-based installer for the hydrological modelling framework, Raven,
    developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
    - huard
