{% set name = "raven-hydro" %}
{% set version = "0.3.1.dev1" %}
{% set sha256 = "90fdb921d43865fdf01f88ed5f801793b9f872f3c1afa3807a2af36ddf8df1a6" %}
{% set raven_version = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  url: https://test-files.pythonhosted.org/packages/58/21/3970b18f518b0a78805edebbdc0653f1c28b028eeebbf5ee7ce8b88a866b/raven_hydro-0.3.1.dev1.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.26
    - make  # [not win]
    - ninja  # [win]
  host:
    - python
    - hatch-fancy-pypi-readme
    - hatchling
    - libnetcdf
    - pip
    - pybind11
    - scikit-build-core >=0.8
    - setuptools-scm >=8.0
    - zlib
  run:
    - python
    - libnetcdf
    - zlib

test:
  imports:
    - raven_hydro
  requires:
    - pip
  commands:
    - pip check
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: http://raven.uwaterloo.ca
  dev_url: https://github.com/Ouranosinc/raven-hydro
  doc_url: http://raven.uwaterloo.ca/files/v{{ raven_version }}/RavenManual_v{{ raven_version }}.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Apache-2.0 and Artistic-2.0
  license_file:
    - LICENSE
    - RavenHydroFramework/LICENSE
  summary: |
    The Python-based installer for the hydrological modelling framework, Raven,
    developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
    - huard
