{% set name = "raven-hydro" %}
{% set version = "3.0.4" %}
{% set revision = "322" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.{{ revision }}

source:
  url: http://www.civil.uwaterloo.ca/jmai/raven/Raven-rev{{ revision }}.zip
  sha256: 96513a51db42c81875347fc4d56cb323ec7feab71a9c4b7f8b03d2144552e582

build:
  number: 1
  skip: true  # [win]
  script:
    # (1) Replace "g++" by $(CXX) in the Makefile
    - sed -i 's/CXX      \:\= g++/# CXX      \:\= g++/g' ./Makefile
    # (2) Rename the app to Raven, not Raven.exe in the Makefile
    - sed -i 's/appname \:\= Raven\.exe/appname \:\= raven/g' Makefile
    - make
    - cp ./raven $PREFIX/bin/raven

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - libnetcdf
  host:
    - libnetcdf
  run:
    - libnetcdf

test:
  commands:
    - test -f $PREFIX/bin/raven
    - raven -v

about:
  home: http://raven.uwaterloo.ca/
  dev_url: https://chyms.nrc.gc.ca/
  doc_url: http://raven.uwaterloo.ca/files/v{{ version }}/RavenManual_v{{ version }}.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Artistic-2.0
  license_file: LICENSE
  summary: The conda-forge binary for the Raven hydrological model developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
