{% set name = "raven-hydro" %}
{% set version = "0.3.1" %}
{% set sha256 = "683f363eb0145452775eb7df00a17b7e5897a404654b198d065423fac2b1b67b" %}
{% set raven_version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake >=3.26.1
    - make  # [not win]
    - ninja >=1.11.0  # [win]
  host:
    - python
    - hatch-fancy-pypi-readme
    - hatchling
    - libnetcdf
    - pip
    - pybind11
    - scikit-build-core >=0.9
    - setuptools-scm >=8.0
    - zlib
  run:
    - python
    - libnetcdf
    - zlib

test:
  imports:
    - raven_hydro
  requires:
    - pip
  commands:
    - pip check
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: https://raven.uwaterloo.ca
  dev_url: https://github.com/Ouranosinc/raven-hydro
  doc_url: https://raven.uwaterloo.ca/files/v{{ raven_version }}/RavenManual_v{{ raven_version }}.pdf
  doc_source_url: https://raven.uwaterloo.ca/Downloads.html
  license: Apache-2.0 and Artistic-2.0
  license_file:
    - LICENSE
    - RavenHydroFramework/LICENSE
  summary: |
    The Python-based installer for the hydrological modelling framework, Raven,
    developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
    - huard
